statbus/models.py
from playhouse.mysql_ext import MySQLConnectorDatabase
from playhouse.flask_utils import FlaskDB
from peewee import *
from .config import DB_USER, DB_PASS, DB_HOST, DB_PORT, DB_NAME


# Setup the mysql connection and flaskdb wrapper.
db = MySQLConnectorDatabase(database = DB_NAME, host = DB_HOST, port = DB_PORT, user = DB_USER, passwd = DB_PASS)
db_wrapper = FlaskDB(None, db)




# Meta model all models should parent from
class DBModel(db_wrapper.Model):
	class Meta:
		database = db

'''
Models!
'''

class Poll_option(DBModel):
	id = IntegerField(unique = True)
	pollid = IntegerField()
	text = CharField()
	minval = IntegerField(null = True)
	maxval = IntegerField(null = True)
	descmin = CharField(null = True)
	descmid = CharField(null = True)
	descmax = CharField(null = True)
	default_percentage_calc = IntegerField(default = 1)


class Poll_question(DBModel):
	id = IntegerField(unique = True)
	polltype = CharField()
	starttime = DateTimeField()
	endtime = DateTimeField()
	question = CharField()
	adminonly = IntegerField()
	multiplechoiceoptions = IntegerField(null = True)
	createdby_ckey = CharField(max_length = 32, null = True)
	createdby_ip = IntegerField()
	dontshow = IntegerField()

	def is_hidden(self):
		return self.adminonly or self.dontshow

	@property
	def link_url(self):
		return f"/poll/{self.pollid}"


class Poll_textreply(DBModel):
	id = IntegerField(unique = True)
	datetime = DateTimeField()
	pollid = IntegerField()
	ckey = CharField(max_length = 32)
	ip = IntegerField()
	replytext = CharField(max_length = 2048)
	adminrank = CharField(max_length = 32, default = "Player")


class Poll_vote(DBModel):
	id = IntegerField(unique = True)
	datetime = DateTimeField()
	pollid = IntegerField()
	optionid = IntegerField()
	ckey = CharField(max_length = 32)
	ip = IntegerField()
	adminrank = CharField(max_length = 32, default = "Player")
	rating = IntegerField(null = True)

statbus/__init__.py
from statbus.app import create_app

__all__ = ("create_app",)

statbus/app.py
from flask import Flask, render_template, request

from statbus.database import db_wrapper
from statbus.cache import cache
from statbus.views import home, polls, rounds


def create_app(test_config = None):

	app = Flask(__name__)
	app.config.from_pyfile("config.py")
	if test_config:
		app.config.update(test_config)

	# Cache and db setup
	cache.init_app(app)
	db_wrapper.init_app(app)

	app.jinja_env.trim_blocks = True
	app.jinja_env.lstrip_blocks = True

	# Blueprints
	app.register_blueprint(home.bp)
	app.register_blueprint(polls.bp)
	app.register_blueprint(rounds.bp)

	# Generic handler
	@app.errorhandler(403)
	@app.errorhandler(404)
	@app.errorhandler(500)
	def internal_error(e):
		return render_template("error.html", error = e), e.code

	return app

statbus/views/home.py
from flask import Blueprint, render_template

bp = Blueprint("home", __name__)


@bp.route("/")
def index():
    return render_template("index.html")

statbus/views/polls.py
from flask import Blueprint, render_template, request, abort
from playhouse.flask_utils import PaginatedQuery
from statbus.database import Poll_question, Poll_option, Poll_vote, Poll_textreply
from peewee import fn, JOIN
from datetime import datetime

bp = Blueprint("polls", __name__)


@bp.route("/poll")
def pollmain():	
	polls = (
		Poll_question.select(
			Poll_question.id,
			Poll_question.question,
			Poll_question.adminonly,
			Poll_question.dontshow,
		)
		.where(Poll_question.adminonly == False, Poll_question.dontshow == False)
	)

	pages = PaginatedQuery(polls, 25, "page")
	
	return render_template("polls/polls.html", pages = pages)


@bp.route("/poll/<int:poll_id>")
def pollid(poll_id):
	poll = Poll_question.select().where(Poll_question.id == poll_id).first()
	if not poll or poll.is_hidden():
		abort(404)

	if poll.polltype == "OPTION":
		votes = (
				Poll_option.select(
					Poll_option.text,
					fn.Count(Poll_vote.id).alias("votes")
				)
				.join(Poll_vote, JOIN.LEFT_OUTER, on = (Poll_option.id == Poll_vote.optionid))
				.where(Poll_vote.pollid == poll_id)
				.group_by(Poll_option.text)
				.order_by(Poll_vote.optionid)
			)

		total = sum([x.votes for x in votes])
		percentages = ["{0:.2f}".format((int(x.votes) / total) * 100) for x in votes]
		
		return render_template("polls/detail_option.html", poll = poll, votes = votes, percentages = percentages, datetime = datetime)

	elif poll.polltype == "TEXT":
		return render_template("polls/detail_text.html", poll = poll)
	
	elif poll.polltype == "NUMVAL":
		return render_template("polls/detail_numval.html", poll = poll)
	
	elif poll.polltype == "MULTICHOICE":
		return render_template("polls/detail_multichoice.html", poll = poll)
	
	elif poll.polltype == "IRV":
		return render_template("polls/detail_irv.html", poll = poll)

	return abort(404)

statbus/views/rounds.py
from flask import Blueprint, render_template, request, abort
from playhouse.flask_utils import PaginatedQuery
from statbus.database import Round
from datetime import datetime, timedelta


bp = Blueprint("rounds", __name__)


@bp.route("/round")
def roundmain():	
	rounds = (
		Round.select(Round.id)
		.order_by(Round.id.desc())
	)

	pages = PaginatedQuery(rounds, 30, "page")
	
	return render_template("rounds/rounds.html", pages = pages)


@bp.route("/round/<int:round_id>")
def roundid(round_id):
	round_info = Round.select().where(Round.id == round_id).first()
	if not round_info:
		abort(404)

	return render_template("rounds/round_info.html", round_info = round_info)


@bp.route("/round/winrates")
def winrates():
	rounds = (
		Round.select(
			Round.game_mode,
			Round.game_mode_result,
			Round.map_name
		)
		.order_by(Round.id.desc())
		.where(Round.initialize_datetime > (datetime.now() - timedelta(days = 30)))
		)

	winrates = None

	return render_template("rounds/winrates.html", winrates = winrates, rounds = rounds)

statbus/templates/base.html
<html>
<head>
	<meta charset="utf-8">
	<title>LaKiller's Statbus</title>
	<meta name="description" content="Meanigless statistics for an even more meaningless game.">
	<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
	<link rel="shortcut icon" type="image/x-icon" href="{{url_for('static', filename='favicon.png')}}"/>
</head>
<body>
	<header>
	{% block header %}
	{% endblock header %}
	</header>
	<div class="container">
		{% block body %}
		{% endblock body %}
	</div>
	<footer><a href="{{url_for('home.index')}}">Home</a> | Made by LaKiller8 | <a href="https://github.com/DominikPanic/lakiller.cz">Source</a></footer>
</body>
</html>

statbus/templates/error.html
{% extends "base.html" %}
{% block header %}
Error
{% endblock header %}
{% block body %}
<h2>Error {{ error.code }}</h2>
<p>{{ error.description }}</p>
{% endblock body %}

statbus/templates/index.html
{% extends "base.html" %}
{% block header %}
	Welcome!
{% endblock header %}
{% block body %}
	<div class="center">
		<p>Please, select a function:</p>
		<a href="{{url_for('polls.pollmain')}}">Polls</a><br>
		<a href="{{url_for('rounds.roundmain')}}">Rounds</a><br>
		<a href="{{url_for('rounds.winrates')}}">Winrates</a>
	</div>
{% endblock body %}

statbus/templates/pages.html
{% if pages.get_page_count() > 1 %}
<div class="pagination">
	{% for i in range(pages.get_page_count()) %}
	  <a href="?page={{i+1}}">{{i+1}}</a>
	{% endfor %}
</div>
{% endif %}

statbus/templates/polls/detail_irv.html
This type of poll is currently not implemented.

statbus/templates/polls/detail_multichoice.html
This type of poll is currently not implemented.

statbus/templates/polls/detail_numval.html
This type of poll is currently not implemented.

statbus/templates/polls/detail_option.html
{% extends "base.html" %}
{% block header %}
	Poll #{{poll.id}}
{% endblock header %}
{% block body %}
	<div class="left">
		<p><b>Details about Poll #{{poll.id}}:</b></p>
		{% include "polls/poll_info.html" %}
		<br>
		{% for vote in votes %}
			<b>{{loop.index}}.</b> {{vote.text}} | {{vote.votes}} votes ({{percentages[loop.index - 1]}}%)<br>
		{% endfor %}
	</div>
{% endblock body %}

statbus/templates/polls/detail_text.html
This type of poll is currently not implemented.

statbus/templates/polls/poll_info.html
<b>Poll start date:</b> {{poll.starttime}}<br>
<b>Poll end date:</b> {{poll.endtime}}<br>
{% if datetime.now() > poll.endtime %}
<b>The poll has ended. {{datetime.now() - poll.endtime}} ago</b><br>
{% else %}
<b>Time remaining:</b> {{poll.endtime - poll.starttime}}<br>
{% endif %}
<b>Started by:</b> {{poll.createdby_ckey}}<br>
<br>
<b>Question:</b> "{{poll.question}}"<br>

statbus/templates/polls/polls.html
{% extends "base.html" %}
{% block header %}
Polls
{% endblock header %}
{% block body %}
<div>
	{% for poll in pages.get_object_list() %}
		<b>Poll #{{poll.id}}</b> {{poll.question}} | <a href='{{poll.link_url}}'>View</a><br>
	{% endfor %}
</div>
{% include "pages.html" %}
{% endblock body %}

statbus/templates/rounds/round_info.html
{% extends "base.html" %}
{% block header %}
	Round #{{round_info.id}}
{% endblock header %}
{% block body %}
	<div class="left">
		<p><b>Details about Round #{{round_info.id}}:</b></p>
		<br>
		{% if round_info.server_port and round_info.server_ip %}
			<b>Server:</b> {{round_info.server_ip}}:{{round_info.server_port}}<br>
		{% endif %}
		{% if round_info.commit_hash %}
			<b>Commit hash:</b> {{round_info.commit_hash}}<br>
		{% endif %}
		{% if round_info.start_datetime %}
			<b>Start time:</b> {{round_info.start_datetime}}<br>
		{% endif %}
		{% if round_info.end_datetime %}
			<b>End time:</b> {{round_info.end_datetime}}<br>
		{% endif %}
		{% if round_info.start_datetime and round_info.end_datetime %}
			<b>Duration:</b> {{round_info.end_datetime - round_info.start_datetime}}<br>
		{% endif %}
		{% if round_info.map_name %}
			<b>Map name:</b> {{round_info.map_name}}<br>
		{% endif %}
		{% if round_info.game_mode %}
			<b>Game mode:</b> {{round_info.game_mode}}<br>
		{% endif %}
		{% if round_info.game_mode_result %}
			<b>Result:</b> {{round_info.game_mode_result}}<br>
		{% endif %}
		{% if round_info.end_state %}
			<b>End state:</b> {{round_info.end_state}}<br>
		{% endif %}
		<div class="back">
			<a href="{{url_for('rounds.roundmain')}}">Back</a>
		</div>
	</div>
{% endblock body %}

statbus/templates/rounds/rounds.html
{% extends "base.html" %}
{% block header %}
	Rounds
{% endblock header %}
{% block body %}
	<div>
	{% for round in pages.get_object_list() %}
		Round ID {{round.id}} | <a href="{{round.link_url}}">View</a><br>
	{% endfor %}
	</div>
{% include "pages.html" %}
{% endblock body %}

statbus/templates/rounds/winrates.html
{% extends "base.html" %}
{% block header %}
	Winrates
{% endblock header %}
{% block body %}
	{{rounds}}<br>
	{% for round in rounds %}
		{{round}}
	{% endfor %}
	<div>
	{% if winrates %}
	{% for winrate_type in winrates %}
		{% for winrate in winrate_type %}
			{{winrate}}
		{% endfor %}
	{% endfor %}	
	</div>
	{% endif %}
{% endblock body %}